### ISSUE TITLE
ConcurrentModificationException in timer executed from AProx

### ISSUE THREAD

**Issue by pkocandr** [Commonjava/partyline#14]
```
Exception in thread "Timer-1" java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at org.commonjava.util.partyline.JoinableFileManager.getActiveLocks(JoinableFileManager.java:155)
    at org.commonjava.util.partyline.JoinableFileManager$ReportingTask.run(JoinableFileManager.java:666)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```

Adding synchronized to getActiveLocks() would probably help, or maybe iterate over a copy of the keySet but that would need to handle keys that disappear before the cycle processes them.

**Comment by jdcasey** [comment]
What version of AProx is this? I think I may have already addressed it, but not sure. I definitely came across a concurrent modification exception in partyline recently, but can't remember specifics.

**Comment by pkocandr** [comment]
Version: 0.25.2-SNAPSHOT | Commit ID: e2828e3 | Built on 2015-11-25 12:17 +0100

The partyline version in it is probably 1.4
