### ISSUE TITLE
NPE in JoinableFileManager

### ISSUE THREAD

**Issue by pkocandr** [Commonjava/partyline#16]
```
Exception in thread "Timer-1" java.lang.NullPointerException
    at org.commonjava.util.partyline.JoinableFileManager.getActiveLocks(JoinableFileManager.java:172)
    at org.commonjava.util.partyline.JoinableFileManager$ReportingTask.run(JoinableFileManager.java:671)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```

**Comment by jdcasey** [comment]
Is this happening in 1.5-SNAPSHOT?

**Comment by pkocandr** [comment]
It was with the latest code, so 1.5-SNAPSHOT, but I'm not sure if it was not caused by low disk space. I can't remember clearly, but I think I discovered such problem shortly after I reported the issue.
